version: '3'

services:
#  app:
#    networks:
#      - default
#      - etcd_network
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - etcd_data:/etcd-data
    command:
      - "etcd"
      - "--data-dir=/etcd-data"
      - "--name=node1"
      - "--initial-advertise-peer-urls=http://etcd:2380,http://127.0.0.1:2380"
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--advertise-client-urls=http://etcd:2379,http://127.0.0.1:2379"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--initial-cluster=node1=http://etcd:2380"
    networks:
      - etcd_network

networks:
  etcd_network:

volumes:
  etcd_data: