version: '3'

services:
  app:
    image: oea-go:latest
    ports:
      - 8888:8080
    env_file:
      - .env
    volumes:
      - ../oea_etcd_private/files:${OEA_FILES}
    command: "-v -s redis:6379"
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
