name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u github.com/go-bindata/go-bindata/go-bindata

    - name: Build
      run: make

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
#        registry: docker.pkg.github.com
        build-args: |
          VERSION=${GITHUB_SHA::8}
        tags: artsafin/oea-go:latest

    - name: Notify in telegram
      run: |
        curl -XPOST \
        --data "chat_id=${{ secrets.TG_DEPLOYBOT_CHAT }}&parse_mode=Markdown" \
        --data "text=Build complete" \
        'https://api.telegram.org/bot${{ secrets.TG_DEPLOYBOT_TOKEN }}/sendMessage'
