name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2.3.1

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build for publishing
      run: make "BUILD_ARGS=-t ghcr.io/artsafin/oea-go:$CI_ACTION_REF_NAME"

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      run: |
        docker image push ghcr.io/artsafin/oea-go:$CI_ACTION_REF_NAME

    - name: Notify in telegram
      run: |
        curl -XPOST \
        --data "chat_id=${{ secrets.TG_DEPLOYBOT_CHAT }}&parse_mode=HTML" \
        --data "text=${GITHUB_JOB} complete in <code>${GITHUB_REPOSITORY}</code>:%0A<code>${GITHUB_REF_NAME}</code> %26lt%3B%3D%26gt%3B <code>${GITHUB_SHA}</code>" \
        'https://api.telegram.org/bot${{ secrets.TG_DEPLOYBOT_TOKEN }}/sendMessage'
